# Generated by Django 5.0.1 on 2024-06-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='technician_profit',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
